# Generated by Django 3.2 on 2021-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeLine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='children',
            field=models.ManyToManyField(related_name='_pipeLine_function_children_+', to='pipeLine.Function'),
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
